---
app_postgres_db: romashlashes
app_postgres_user: romashlashes

app_http_port: 80
app_https_port: 443
app_server_name: "dev.romashlashes.test"

app_django_debug: false

app_django_allowed_hosts:
  - "dev.romashlashes.test"
  - "192.168.0.185"
  - "localhost"
  - "127.0.0.1"

app_django_csrf_trusted_origins:
  - "https://dev.romashlashes.test"

app_django_secure_ssl_redirect: false
app_django_session_cookie_secure: false
app_django_csrf_cookie_secure: false

app_django_secure_hsts_seconds: 0
app_django_secure_hsts_include_subdomains: false
app_django_secure_hsts_preload: false
