# Generated by Django 6.1.1 on 2026-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='viber_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='viber_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
