---
gitlab_tls_registry_gitlab_url: "https://gitlab.int.romashlashes.by"
gitlab_tls_registry_registry_url: "https://registry.int.romashlashes.by"

gitlab_tls_registry_cert_src: "{{ inventory_dir }}/../.secrets/gitlab/gitlab-registry.crt"
gitlab_tls_registry_key_src: "{{ inventory_dir }}/../.secrets/gitlab/gitlab-registry.key"
gitlab_tls_registry_ca_src: "{{ inventory_dir }}/../.secrets/gitlab/romashlashes-rootCA.crt"

gitlab_tls_registry_cert_dest: "/etc/gitlab/ssl/gitlab-registry.crt"
gitlab_tls_registry_key_dest: "/etc/gitlab/ssl/gitlab-registry.key"
gitlab_tls_registry_ca_dest: "/usr/local/share/ca-certificates/romashlashes-rootCA.crt"
