all:
  children:
    app:
      children:
        dev:
          hosts:
            dev-01:
              ansible_host: 192.168.0.185

        stage:
          hosts:
            stage-01:
              ansible_host: 192.168.0.184

        prod:
          hosts:
            prod-01:
              ansible_host: 192.168.0.183

    ci:
      hosts:
        ci-01:
          ansible_host: 192.168.0.186

    gitlab:
      hosts:
        gitlab-01:
          ansible_host: 192.168.0.187

    mirror:
      hosts:
        mirror-01:
          ansible_host: 192.168.0.188

    dns:
      children:
        dns_primary:
          hosts:
            dns-01:
              ansible_host: 192.168.0.10
              dns_bind_server_role: primary

        dns_secondary:
          hosts:
            dns-02:
              ansible_host: 192.168.0.11
              dns_bind_server_role: secondary
