all:
  children:
    dev:
      hosts:
        dev-01:
          ansible_host: 192.168.0.185

    stage:
      hosts:
        stage-01:
          ansible_host: 192.168.0.184

    prod:
      hosts:
        prod-01:
          ansible_host: 192.168.0.183

    ci:
      hosts:
        ci-01:
          ansible_host: 192.168.0.186