---
- name: Update CA certificates
  ansible.builtin.command:
    cmd: update-ca-certificates
  changed_when: true

- name: Reconfigure GitLab
  ansible.builtin.command:
    cmd: gitlab-ctl reconfigure
  changed_when: true

- name: Reload GitLab nginx
  ansible.builtin.command:
    cmd: gitlab-ctl hup nginx
  changed_when: true

- name: Reload GitLab registry
  ansible.builtin.command:
    cmd: gitlab-ctl hup registry
  changed_when: true
