---
app_server_name: "stage.int.romashlashes.by"

app_django_allowed_hosts:
  - "stage.int.romashlashes.by"
  - "192.168.0.184"
  - "localhost"
  - "127.0.0.1"

app_django_csrf_trusted_origins:
  - "https://stage.int.romashlashes.by"

app_django_secure_hsts_seconds: 0
app_django_secure_hsts_include_subdomains: false
app_django_secure_hsts_preload: false
